import { months } from "@hebcal/core";

export interface IDay {
    month: keyof typeof months | "ADAR";
    startDay: number;
    endDay: number;
    description: string;
    descriptionIl?: string;
    source: string;
    dayBefore: boolean;
}

export const days: IDay[] = [
    {
        month: "TISHREI",
        startDay: 1,
        endDay: 2,
        description: "Rosh Hashana",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 9,
        endDay: 9,
        description: "Erev Yom Kippur",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 10,
        endDay: 10,
        description: "Yom Kippur",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 11,
        endDay: 14,
        description: "between Yom Kippur and Sukkot",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 15,
        endDay: 15,
        description: "Sukkot",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 16,
        endDay: 16,
        descriptionIl: "Sukkot (Chol Hamoed)",
        description: "Sukkot",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 17,
        endDay: 21,
        description: "Sukkot (Chol Hamoed)",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 22,
        endDay: 22,
        description: "Shmini Atzeret",
        descriptionIl: "Simchat Torah",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 23,
        endDay: 23,
        description: "Simchat Torah",
        descriptionIl: "between Sukkot and Rosh Chodesh Cheshvan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "TISHREI",
        startDay: 24,
        endDay: 29,
        description: "between Sukkot and Rosh Chodesh Cheshvan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "KISLEV",
        startDay: 25,
        endDay: 30,
        description: "Chanukah",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "TEVET",
        startDay: 1,
        endDay: 2,
        description: "Chanukah",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "SHVAT",
        startDay: 15,
        endDay: 15,
        description: "Tu Bishvat",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "ADAR",
        startDay: 14,
        endDay: 14,
        description: "Purim",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "ADAR",
        startDay: 15,
        endDay: 15,
        description: "Shushan Purim",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "ADAR_I",
        startDay: 14,
        endDay: 14,
        description: "Purim Katan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "ADAR_I",
        startDay: 15,
        endDay: 15,
        description: "Shushan Purim Katan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "ADAR_II",
        startDay: 14,
        endDay: 14,
        description: "Purim",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "ADAR_II",
        startDay: 15,
        endDay: 15,
        description: "Shushan Purim",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "NISAN",
        startDay: 2,
        endDay: 14,
        description: "Chodesh Nisan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "NISAN",
        startDay: 15,
        endDay: 21,
        description: "Pesach",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: true,
    },
    {
        month: "NISAN",
        startDay: 22,
        endDay: 22,
        description: "Pesach",
        descriptionIl: "Chodesh Nisan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: true,
    },
    {
        month: "NISAN",
        startDay: 23,
        endDay: 29,
        description: "Chodesh Nisan",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "IYYAR",
        startDay: 14,
        endDay: 14,
        description: "Pesach Sheni",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "IYYAR",
        startDay: 18,
        endDay: 18,
        description: "Lag Ba'omer",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "IYYAR",
        startDay: 28,
        endDay: 28,
        description: "Yom Yerushalaim",
        source: "Peninei_Halakhah%2C_Prayer.21.7.4",
        dayBefore: true,
    },
    {
        month: "SIVAN",
        startDay: 2,
        endDay: 2,
        description: "Yom Hameyuchas",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "SIVAN",
        startDay: 3,
        endDay: 5,
        description: "Shloshet Yemei Hagbala",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "SIVAN",
        startDay: 6,
        endDay: 6,
        description: "Shavuot",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "SIVAN",
        startDay: 7,
        endDay: 7,
        description: "Shavuot",
        descriptionIl: "the week after Shavuot",
        source: "Peninei_Halakhah%2C_Prayer.21.7.2",
        dayBefore: false,
    },
    {
        month: "SIVAN",
        startDay: 8,
        endDay: 12,
        description: "the week after Shavuot",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
    {
        month: "AV",
        startDay: 15,
        endDay: 15,
        description: "Tu B'av",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: true,
    },
    {
        month: "ELUL",
        startDay: 29,
        endDay: 29,
        description: "Erev Rosh Hashana",
        source: "Peninei_Halakhah%2C_Prayer.21.7.3",
        dayBefore: false,
    },
];
