name: Publish Static Files
on: [push]
jobs:
  Publish-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        # You may pin to the exact commit or the version.
        # uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
        uses: oven-sh/setup-bun@v2
      - run: echo 'Bun setup successfully'
      - run: bun run build
      - run: echo 'Build successful'
